name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black mypy

      - name: Run linting and formatting checks
        run: |
          echo "Vérification du code avec Flake8..."
          flake8 --config=config/.flake8 .
          echo "Vérification du formatage avec Black..."
          black --check .
          echo "Vérification du typage statique avec mypy..."
          mypy --config-file=config/mypy.ini .

      - name: Run tests with coverage
        run: |
          echo "Exécution des tests avec coverage..."
          # Exécute les tests et collecte la couverture
          coverage run -m pytest --maxfail=1 --disable-warnings -q
          # Affiche un rapport texte et échoue si la couverture est inférieure à 80%
          coverage report --fail-under=80
          # Génère un rapport HTML dans le dossier htmlcov (optionnel)
          coverage html

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
